In [1]:
%matplotlib inline
import xarray as xr
import numpy as np 
import os 

In [2]:
# load some ERA-5 data, using incorrect precip data just for example purposes 
direc = '/gcs/impactlab-data/climate/source_data/ERA-5/day/precip_total/v1.0'
filename = 'precip_total_daily_2000-2000.nc'

In [4]:
day_data = xr.open_dataset(os.path.join(direc, filename))
day_slice = day_data.loc[dict(time=slice("2000-01-01", "2000-01-03"))]

# resample it to hourly for example 
day_slice_hourly = day_slice.resample(time='1H').pad()

In [5]:
# roll timestamps 
data_rolled = day_slice_hourly['precip_total'].roll(time=-1, roll_coords=True)

In [6]:
# check the values for Seattle 
day_slice_hourly['precip_total'].sel(latitude=47.6, longitude=-122.33, method='nearest').values

array([5.2340329e-05, 5.2340329e-05, 5.2340329e-05, 5.2340329e-05,
       5.2340329e-05, 5.2340329e-05, 5.2340329e-05, 5.2340329e-05,
       5.2340329e-05, 5.2340329e-05, 5.2340329e-05, 5.2340329e-05,
       5.2340329e-05, 5.2340329e-05, 5.2340329e-05, 5.2340329e-05,
       5.2340329e-05, 5.2340329e-05, 5.2340329e-05, 5.2340329e-05,
       5.2340329e-05, 5.2340329e-05, 5.2340329e-05, 5.2340329e-05,
       3.6637858e-04, 3.6637858e-04, 3.6637858e-04, 3.6637858e-04,
       3.6637858e-04, 3.6637858e-04, 3.6637858e-04, 3.6637858e-04,
       3.6637858e-04, 3.6637858e-04, 3.6637858e-04, 3.6637858e-04,
       3.6637858e-04, 3.6637858e-04, 3.6637858e-04, 3.6637858e-04,
       3.6637858e-04, 3.6637858e-04, 3.6637858e-04, 3.6637858e-04,
       3.6637858e-04, 3.6637858e-04, 3.6637858e-04, 3.6637858e-04,
       3.8295984e-06], dtype=float32)

In [7]:
# compare to the rolled ones 
data_rolled.sel(latitude=47.6, longitude=-122.33, method='nearest').values

array([5.2340329e-05, 5.2340329e-05, 5.2340329e-05, 5.2340329e-05,
       5.2340329e-05, 5.2340329e-05, 5.2340329e-05, 5.2340329e-05,
       5.2340329e-05, 5.2340329e-05, 5.2340329e-05, 5.2340329e-05,
       5.2340329e-05, 5.2340329e-05, 5.2340329e-05, 5.2340329e-05,
       5.2340329e-05, 5.2340329e-05, 5.2340329e-05, 5.2340329e-05,
       5.2340329e-05, 5.2340329e-05, 5.2340329e-05, 3.6637858e-04,
       3.6637858e-04, 3.6637858e-04, 3.6637858e-04, 3.6637858e-04,
       3.6637858e-04, 3.6637858e-04, 3.6637858e-04, 3.6637858e-04,
       3.6637858e-04, 3.6637858e-04, 3.6637858e-04, 3.6637858e-04,
       3.6637858e-04, 3.6637858e-04, 3.6637858e-04, 3.6637858e-04,
       3.6637858e-04, 3.6637858e-04, 3.6637858e-04, 3.6637858e-04,
       3.6637858e-04, 3.6637858e-04, 3.6637858e-04, 3.8295984e-06,
       5.2340329e-05], dtype=float32)

In [8]:
# resample to daily, eliminate the very last timestamp since it's the first timestamp rolled to the end 
data_sum = data_rolled[:-1].resample(time='1D', closed='right').sum(dim='time')

In [9]:
# look at the daily values 
data_sum.sel(latitude=47.6, longitude=-122.33, method='nearest').values

array([0.00157021, 0.00843054], dtype=float32)

In [10]:
# make sure that this sum is equal to the first value in the array above 
data_rolled.sel(latitude=47.6, longitude=-122.33, method='nearest').values[:24].sum()

0.0015702061